### PR TITLE
Add multiarch support

### PR DESCRIPTION
**Pull request by chase-qi**
Added image architecture and machine subarchitecture parameters. The
values should be set in erp-test-automation repo by host group.

Signed-off-by: Chase Qi <chase.qi@linaro.org>

### CODE REVIEW

**Comment by chase-qi** [comment]
@danrue @mwasilew @gemagomez would you please give it a review? 

Note: I think merging wouldn't break anything as we have role version set in requirement.

**Comment by chase-qi** [comment]
Test run output example https://pastebin.linaro.org/view/45bda457

**Comment by danrue** [comment]
This looks good. Please also update the README and be sure to mention the version compatibilities (maybe add changelog section to readme?) I added write access so you can merge this when you're read and make a release (using github interface).

**Review by danrue — APPROVED** [review]

**Comment by chase-qi** [comment]
@danrue , thanks a lot for your review! I actually updated README.md, but I forgot to include it. I just created a new CHANGELOG.md file to document the changes for the future releases.

**Pull request merged**
